language: node_js
git:
  depth: 1
node_js:
  - '8'
sudo: false
script:
  # generate the site
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  target-branch: gh-pages
  github-token:
    secure: # TOKEN
  on:
    repo: microluxe20/microluxe20.com
    tags: true
